<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <!-- タスクトレイの NotifyIcon に使用 -->
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Brightness</RootNamespace>
    <AssemblyName>Brightness</AssemblyName>
    <ApplicationIcon>Brightness.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Brightness.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="10.0.0" />
  </ItemGroup>

</Project>
